title: Pedro Henrique Martins # your name (or website title) here
logo: "/images/profile.jpeg?raw=1x" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="mailto:pedrohenriqueamartins@gmail.com">Email</a> <br />
  <a href="https://scholar.google.pt/citations?user=y2bVjBIAAAAJ&hl=pt-PT">Google Scholar</a> <br />
  <a href="https://www.linkedin.com/in/pedro-henrique-alves-martins-a0969937/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
