title: Pedro Henrique Martins # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Machine Learning and NLP PhD student at Instituto Superior Técnico, University of Lisbon. I'm also a researcher at Instituto de Telecomunicações. My advisors are [Prof. André Martins](https://andre-martins.github.io/) and [Prof. Zita Marinho](https://www.cs.cmu.edu/~zmarinho/).


  <br><br>
  I'm very enthusiastic about Machine Learning and Natural Language Processing, being my main research interests Natural Language Generation and Deep Latent Variable Models.
  <br><br>
  <a href="https://www.linkedin.com/in/pedro-henrique-alves-martins-a0969937/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
